import type {
  AiConfidence,
  AiOperationType,
  ApiErrorCode,
} from "@daily-assistant/api-contracts";

export const FAKE_AI_PROVIDER_ID = "fake-provider";
export const FAKE_AI_MODEL_ID = "fake-model";

export const FAKE_AI_PROVIDER_SCENARIOS = [
  "TRANSACTION_SUCCESS",
  "CALENDAR_EVENT_SUCCESS",
  "TASK_SUCCESS",
  "REMINDER_SUCCESS",
  "TRIP_SUCCESS",
  "UNCERTAIN",
  "CONTROLLED_FAILURE",
] as const satisfies readonly FakeAiProviderScenario[];

/**
 * Private Fake Provider scenario control. This is an internal implementation
 * detail and must never be smuggled into AiProviderInput; the frozen provider
 * input whitelist stays exactly as defined in the shared AI contract.
 */
export type FakeAiProviderScenario =
  | "TRANSACTION_SUCCESS"
  | "CALENDAR_EVENT_SUCCESS"
  | "TASK_SUCCESS"
  | "REMINDER_SUCCESS"
  | "TRIP_SUCCESS"
  | "UNCERTAIN"
  | "CONTROLLED_FAILURE";

export interface FakeAiProviderConfiguration {
  scenario: FakeAiProviderScenario;
}

/**
 * A candidate operation generated by the Fake Provider. The status is locked
 * to "PENDING" so the provider can never emit ACCEPTED or APPLIED: acceptance
 * and application belong to later proposal/operation orchestration and the
 * separate final user confirmation.
 */
export interface FakeAiOperationCandidate {
  operationType: AiOperationType;
  status: "PENDING";
  confidence: AiConfidence;
  fields: Record<string, unknown>;
  clarification: string | null;
}

export interface FakeAiProviderSuccessResult {
  resultType: "SUCCESS";
  providerId: string;
  modelId: string;
  operations: FakeAiOperationCandidate[];
}

export interface FakeAiProviderUncertainResult {
  resultType: "UNCERTAIN";
  providerId: string;
  modelId: string;
  operations: FakeAiOperationCandidate[];
  clarification: string;
  missingFields: string[];
}

export type FakeAiProviderResult =
  FakeAiProviderSuccessResult | FakeAiProviderUncertainResult;

export interface FakeAiProviderErrorDetails {
  providerId: string;
  modelId: string;
  errorCategory: "CONTROLLED_FAILURE";
  errorCode: ApiErrorCode;
  message: string;
}
